---
# This play cleans up content views and leaves only a configured amount remaining
- name: Publish the configured Content Views and Composite Content Views
  hosts: all
  connection: local
  roles:
    - role: redhat.satellite.content_view_version_cleanup
      vars:
        satellite_server_url: "{{ sat_server_url }}"
        satellite_username: "{{ sat_publisher_username }}"
        satellite_password: "{{ sat_publisher_password }}"
        satellite_organization: "{{ sat_organization }}"
        satellite_validate_certs: "{{ sat_validate_certs }}"
        satellite_content_view_version_cleanup_keep: "{{ num_cvs_to_keep }}"
        search: "{{ cv_search }}"
        