---
- hosts: all
  connection: local
  gather_facts: false
#  collections:
#    - redhat.satellite
  tasks:
  - name: Publish the new content view version
    redhat.satellite.content_view_version:
      username: "{{ sat_publisher_username }}"
      password: "{{ sat_publisher_password }}"
      server_url: "{{ sat_server_url }}"
      content_view: "{{ cv_name }}"
      organization: "{{ sat_organization }}"
      validate_certs: "{{ sat_validate_certs }}"
      description: "{{ description }}"
